version: "3.1"
services:
  database:
    restart: always
    image: mariadb:10.5
    ports:
      - "6000:3306"
    environment:
      - "MARIADB_ROOT_USERNAME=${USER_NAME}"
      - "MARIADB_ROOT_PASSWORD=${USER_PASS}"